slam_toolbox:
  ros__parameters:

    # Plugin ayarlar覺
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Topic ayarlar覺 (Harmonic Bridge ile uyumlu olmal覺)
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping # Haritalama modu

    # Harita kalitesi
    map_file_name: serial_map
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true

    # Debugging
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 # 50Hz
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0 # Lidar menzili
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 # Bellek ayar覺
    enable_interactive_mode: true
